name: "Update data"
on:
  schedule:
    - cron: '42 1 * * 1'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Update clouds"
        run: |
          SERVICETAGS_PUBLIC_URL=$(curl -s 'https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519' | grep -Eo '"https://[^"]*ServiceTags_Public[^"]*"' | head -n 1 | cut -d '"' -f 2)
          if [ -z "$SERVICETAGS_PUBLIC_URL" ]
          then
            echo "Downloading from $SERVICETAGS_PUBLIC_URL"
            curl -s $SERVICETAGS_PUBLIC_URL | jq . > network/ServiceTags_Public.json
          else
            echo "Error: ServiceTags_Public download location couldn't be found, check https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519 for issues"
            exit 1
          fi

      - name: "Update JSON with Graph credentials"
        run: |
          AZURE_TOKEN=$( \
            curl \
            -d grant_type=client_credentials \
            -d client_id=${AZURE_CLIENT_ID} \
            -d client_secret=${AZURE_CLIENT_SECRET} \
            -d scope=https://graph.microsoft.com/.default \
            -d resource=https://graph.microsoft.com \
            https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/token \
            | jq -j .access_token)
          curl -H "Authorization: Bearer ${AZURE_TOKEN}" -H "Content-Type: application/json" https://graph.microsoft.com/beta/roleManagement/directory/roleDefinitions | jq . > info/roles.graph.json
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: "Update JSON and Markdown"
        run: |
          curl https://endpoints.office.com/endpoints/worldwide?clientrequestid=7f74198b-51f7-4caf-ad3f-736180888dd7 > network/office_endpoints_worldwide.json
          python info/roles.json.py

      - name: Create PR
        id: push_update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          echo "Start."
          # Configure git and Push updates
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git config pull.rebase false
          branch=automated-update-$GITHUB_RUN_ID
          git checkout -b $branch
          message='Automated update'
          # Add / update and commit
          git add */**
          git commit -m 'Automated update [skip ci]' || export NO_UPDATES=true
          # Push
          if [ "$NO_UPDATES" != "true" ] ; then
              git push origin "$branch"
              gh pr create --title "$message" --body "$message"
          fi
